load("@rules_python//python:defs.bzl", "py_binary")
load(
    "//compiler-tuning/register-allocation:register_allocation_report.bzl",
    "coralnpu_register_allocation_report",
)

package(
    default_visibility = ["//visibility:public"],
)

coralnpu_register_allocation_report(
    name = "linalg_register_reports",
    srcs = ["//tests/models/linalg:check_mlir_files"],
)

py_binary(
    name = "benchmark_register_usage",
    srcs = ["benchmark_register_usage.py"],
    args = ["$(locations :linalg_register_reports)"],
    data = [
        ":linalg_register_reports",
    ],
    deps = [],
)
